# Generated by Django 5.2.3 on 2025-07-08 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSRRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('police_station', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(default='Request Received', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_response_data', models.TextField(blank=True, null=True)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('forwarded_to_station_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
