# Generated by Django 5.2.3 on 2025-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csrrequest',
            name='police_station',
        ),
        migrations.AddField(
            model_name='csrrequest',
            name='police_station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='csrrequest',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='csrrequest',
            name='sent_to_provider_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csrrequest',
            name='station_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='csrrequest',
            name='station_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
